server:
  port: 8000



spring:
  profiles: peer1
  name: eureka-server

eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8001/eureka/

