eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/
server:
  port: 5001
spring:
  application:
    name: service-zuul
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411
zuul:
  routes:
    api-hello:
      path: /api-hello/**
      serviceId: service-hello
    api-hi:
      path: /api-hi/**
      serviceId: service-hi
  host:
        connect-timeout-millis: 10000
        socket-timeout-millis: 60000

