eureka:
  client:
    serviceUrl:
      defaultZone:  http://peer1:8000/eureka/,http://peer2:8001/eureka/
server:
  port: 9411
spring:
  application:
    name: zipkin-server
zipkin:
  storage:
    type: elasticsearch
    StorageComponent: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      max-requests: 30
      index: zipkin
      index-shards: 3
      index-replicas: 1
      hosts: localhost:9200
#spring.sleuth.sampler.percentage: 1.0