eureka:
  client:
    serviceUrl:
      defaultZone:  http://peer1:8000/eureka/,http://peer2:8001/eureka/
server:
  port: 9411
spring:
  application:
    name: zipkin-server
#spring.sleuth.sampler.percentage: 1.0